include ../../mk/spksrc.common.mk

SPK_NAME = synocli-file
SPK_VERS = 1.0
SPK_REV = 1
SPK_ICON = src/synocli-file.png

DEPENDS = cross/jdupes cross/less

MAINTAINER = m4tt075
DESCRIPTION = "SynoCli File Tools provides a set of small command-line utilities: jdupes, less. Credits to Sebastian Schmidt \(publicarray\) for icons"
DISPLAY_NAME = SynoCli File Tools
STARTABLE = no
CHANGELOG = "1. Initial release"

#TODO
#HOMEPAGE   = https://github.com/SynoCommunity/spksrc/wiki/FAQ-SynoCliFile
LICENSE    = Mixed

SERVICE_SETUP = src/service-setup.sh

include ../../mk/spksrc.spk.mk
