SPK_NAME = ffmpeg
SPK_VERS = 4.1.2
SPK_REV = 12
SPK_ICON = src/ffmpeg.png
CHANGELOG = "1. Update ffmpeg to 4.1.2"

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = m4tt075
DESCRIPTION = FFmpeg is a complete, cross-platform solution to record, convert and stream audio and video. It includes libavcodec - the leading audio/video codec library.
DISPLAY_NAME = ffmpeg
STARTABLE = no

HOMEPAGE = http://www.ffmpeg.org/
LICENSE  = GPLv3

include ../../mk/spksrc.spk.mk
